### ISSUE TITLE
When tapping 'return' on mobile devices, allow for the keyboard to close and the chat to display in full again

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-live-chat-support#155]

**Comment by JarrydLong** [comment]
Note* Only experienced in iOS

**Comment by DylanCodeCabin** [comment]
I have researched this diligently and from my research we cannot control (close/open) the keyboard from within JavaScript. 

The browser is responsible for handling these triggers. The reason these components are not directly accessible is simply due to the fact that this would infringe the users privacy by forcing an action upon a user he/she may not want to take. 

There may be a way of 'hacking' this using jQuery trigger calls, however I believe this could cause usability issues, and create unstable JS which I would not advise. 

I have spoke to project lead @JarrydLong and he agrees with me on this point. 

We are closing this issue.
